### ISSUE TITLE
Features to Add

### ISSUE THREAD

**Issue by RussianRonin** [mkafrin/PolyZone#1]
- Z as part of printout
- Undo point as part of creation

**Comment by mkafrin** [comment]
- Delete last saved poly command
- Maybe cancel command to cancel a messed up zone instead of saving it
- Maybe add outer bounding box to debug view

**Comment by RussianRonin** [comment]
Added undo command and cancel command in https://github.com/mkafrin/PolyZone/commit/e85359100d9eeab9626d61519e09706252579bb1

**Comment by RussianRonin** [comment]
Added Z as part of printout in https://github.com/mkafrin/PolyZone/commit/7fa1c459f7b1584a38e21f15db8b24b0d7759126

**Comment by mkafrin** [comment]
All features added or decided against implementing
