### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by Charles11130** [mkafrin/PolyZone#101]
![image](https://github.com/mkafrin/PolyZone/assets/168089975/7e333c02-9c08-4736-8554-a40880de79d1)
![image](https://github.com/mkafrin/PolyZone/assets/168089975/9ee3b4dc-41ce-43ba-8565-547c55807e27)
Hello, I have this debug that appears, impossible to delete..

**Comment by mkafrin** [comment]
This isn't how PZ even displays debug of zones, so I don't think it's related. Even if it was, there's no zones created in PZ, so some other resource would have to create a zone and turn it's debug on. Either way, this is unrelated to PZ itself.

**Comment by Charles11130** [comment]
I don't agree, I removed all my scripts from the server to find the problem, it definitely comes from yours. When I put the old version of PolyZone it no longer appears...

**Comment by mkafrin** [comment]
What coordinates is this at? And you're saying you had a blank server with just PolyZone started and you saw this? I can't even imagine how that'd be possible since this isn't how debug drawing works in PZ, but I can check it if you can provide the coords.

**Comment by Charles11130** [comment]
Hello , heading = 114.98358917236328, vector4(-683.07604980469, -1102.7947998047, 14.525598526001, 114.98374176025),
vector3(-683.07604980469, -1102.7947998047, 14.525598526001)

**Comment by Charles11130** [comment]
Hello i have solved this issue .
In qb-target /client/lua  line 1389 debugPoly = true ====>> false .
CreateThread(function()
	exports['qb-target']:AddBoxZone('test', vector3(-683.14, -1102.76, 14.53), 2.0, 2.0, {
		name = 'test',
		debugPoly = true,
		minZ = 13.53,
		maxZ = 15.53,
	}, {
		options = {
			{
				type = 'client',
				event = 'qb-ambulancejob:stash',
				icon = 'fa fa-hand',
				label = 'Open Stash'
			}
		}
	})
end)
