### ISSUE TITLE
Polyzone debug lines

### ISSUE THREAD

**Issue by azurerosepetal** [mkafrin/PolyZone#106]
Hey, how do i remove the red debug lines made in the polyzone creator? Unsure how to get rid of it.

**Comment by willbarrowgaming** [comment]
Have you figured this out by chance.  Im having same issue and its driving me nuts

**Comment by azurerosepetal** [comment]
I dont remember exactly but I THINK it was when I went into my fivem server folder, found the "polyzone_created_zones" text document, and deleted the corresponding incomplete zone! 

I hope that works for you lol

**Comment by willbarrowgaming** [comment]
I appreciate that.  I spent like 7 hours trying to figure it out.  Ended up deleting my server and starting fresh today.  It was in literally line 4 in my config.lua for my mechanic script, lol.  Debug was set to true.  Not sure how i missed that the 1000 times I looked at the lua.
