### ISSUE TITLE
field 'output' error

### ISSUE THREAD

**Issue by Trvp-Boss** [mkafrin/PolyZone#110]
Ever since i deleted polyzone_created_zones.txt and created a new text file with the same name "polyzone_created_zones.txt" I keep getting this error once I create a zone and type /pzfinish . I tried deleting polyzone file and redownloading new updates aswell as restarting the server. I cant create a zone due to this error. 
![Screenshot 2024-12-24 130347](https://github.com/user-attachments/assets/afa052b5-c205-4a2e-9b94-ccf84d972ffa)

**Comment by subhampro** [comment]
@Trvp-Boss  I updated My repo ! Please download My resource and inform me is that working or not !  (Just Fixed all Errors !!)

https://github.com/subhampro/PolyZone

**Comment by subhampro** [comment]
*In my script .txt file will create Inside the PolyZone Script folder (Not On Root Folder)

**Comment by mkafrin** [comment]
@Trvp-Boss Heads up, the fix was upstreamed into the latest release if you want to switch back to the official version.
