### ISSUE TITLE
Creation possible ctrl button change

### ISSUE THREAD

**Issue by mkafrin** [mkafrin/PolyZone#33]
Look into changing ctrl from being a "hold down to make slower" function to instead "press ctrl to toggle through speeds"

**Comment by JiminyKroket** [comment]
Sorry to interject into not my issue, you should be able to simply turn IsControlPressed/IsDisabledControlPressed to IsControlJustPressed/IsDisabledControlJustPressed, correct?

**Comment by mkafrin** [comment]
No, changing it to IsControlJustPressed would just mean that the slow down would only occur on the single frame you pressed control. Instead the functionality that this is targeting is a toggle through a series of speeds. So you pressed ctrl once and it goes to half speed permanently, then you press it again and it goes to 1/4th speed, then again and 1/8th, etc., until you get to the lowest speed and you press ctrl one more time and it cycles back to normal speed.

Though this feature probably won't make it in to the resource, at least for a little while.
