### ISSUE TITLE
Failed Load

### ISSUE THREAD

**Issue by JiminyKroket** [mkafrin/PolyZone#36]
![image](https://user-images.githubusercontent.com/50643200/104104395-7d2dd280-526d-11eb-8575-07399c743308.png)
I unfortunately am no longer able to use latest artifacts, so had to install the Cayo Perico streamed map, which requires your PolyZone. Upon initial installation I receive this message, with no indication of why it failed. If I restart polyzone while in game, I get no error though. Is there something I'm missing like waiting for spawn?

**Comment by mkafrin** [comment]
Hmm, two thoughts:

1. Did you "ensure PolyZone" in your server.cfg before ensuring the cayoperico resource?
2. Did you extract PolyZone.zip into the top level of the resources folder? (if not, what does the path to the resource look like)

**Comment by mkafrin** [comment]
@JiminyKroket Hmm, two thoughts:

1. Did you "ensure PolyZone" in your server.cfg before ensuring the cayoperico resource?
2. Did you extract PolyZone.zip into the top level of the resources folder or only under further folders that have square brackets (i.e. resources/[stuff]/PolyZone)? If not, what does the path to the resource look like?

**Comment by mkafrin** [comment]
@JiminyKroket Still having issues? If not I'll close this tomorrow.

**Comment by JiminyKroket** [comment]
I am very sorry for the delayed response.
![image](https://user-images.githubusercontent.com/50643200/104531799-953a8480-55d4-11eb-9662-0ced90d15d4c.png)
I am ensuring polyzone above the cayoperico script. I did rename them both to lowercase when removing the "-master" from the zip downloads, is that not okay for polyzone?
![image](https://user-images.githubusercontent.com/50643200/104531832-9cfa2900-55d4-11eb-94cb-143d7647d65a.png)
Here is the directory of where polyzone is stored in my resources folder

**Comment by mkafrin** [comment]
Yeah, the lowercase is the issue. PolyZone should be named exactly as "PolyZone". That's how it is imported, so if you name it something different, it won't find the scripts and fail to load.

**Comment by JiminyKroket** [comment]
You are 100 percent correct, I'm sorry to have bothered you.

**Comment by mkafrin** [comment]
@JiminyKroket NP, glad we could fix it.
