### ISSUE TITLE
[QUESTION] Can we detect if object is inOut zone ?

### ISSUE THREAD

**Issue by FreakOutModz** [mkafrin/PolyZone#41]
Any to detect a object in zone ?

If we use example with pinckage:
`
https://pastebin.com/Pmz6aM7b
`

How can I make `soccerBall` if it's in zone ?

Thanks!

**Comment by mkafrin** [comment]
https://github.com/mkafrin/PolyZone/wiki/ComboZone#ispointinsideonpointinoutonplayerinout

`onPointInOut` allows you to pass any arbitrary function to get the `point` that is being tested. In your code, you are passing in `PolyZone.getPlayerPosition`, but you could just as easily do the following:

```lua
pinkcage:onPointInOut(function() return GetEntityCoords(soccerBall) end, function(isPointInside, point)
    if isPointInside then
	DeleteObject(soccerBall)
    else
	print('out')
    end
end)
```

**Comment by FreakOutModz** [comment]
Thanks for info, will take a look at it.
