### ISSUE TITLE
[Not an issue] Delete all vehicles in zone

### ISSUE THREAD

**Issue by Oldarorn** [mkafrin/PolyZone#42]
Hello, I'd like to use a karting map and I've a problem inside it. Some npcs vehicles are spawning, I'd like to know if there a way with PolyZone to delete each vehicle which is not whitelisted in my config ? (I know how to configure a WL but I don't know what I should do to use my PolyZone like this)

Thank for your help, this tool is amazing !

**Comment by mkafrin** [comment]
So sorry for the wait. I saw this earlier but it slipped my mind.

Regarding the question, I'm unaware of if there's an event that is triggered from FiveM whenever a vehicle is spawned on the client (I would guess there isn't), so probably the only way to do this is to periodically loop through the vehicles in scope (using [GetGamePool](https://docs.fivem.net/natives/?_0x2B9D4F50) maybe?) and for each of those vehicles, get their position and use isPointInside(position) to check if they're inside the zone or not.

**Comment by Oldarorn** [comment]
Haha it's ok, your answer cames as fast as I hoped :) 

I'll try it and give you a feedback about it ! Thanks

**Comment by Oldarorn** [comment]
It was perfect, thanks again for your help <3

**Comment by martin-lechene** [comment]
> So sorry for the wait. I saw this earlier, but it slipped my mind.
> 
> Regarding the question, I'm unaware of if there's an event that is triggered from FiveM whenever a vehicle is spawned on the client (I would guess there isn't), so probably the only way to do this is to periodically loop through the vehicles in scope (using [GetGamePool](https://docs.fivem.net/natives/?_0x2B9D4F50) with the pool `CVehicle` maybe?) and for each of those vehicles, get their position and use `isPointInside(position)` on the zone to check if they're inside the zone or not. Pseudo code below:
> 
> ```lua
> local vehicles = GetGamePool("CVehicle")
> for _, vehicle in ipairs(vehicles) do
>   if not vehicleInWhitelist(vehicle) and zone:isPointInside(GetEntityCoords(vehicle)) then
>     -- delete vehicle
>   end
> end
> ```

You can add other information because i found difficult for create a good algo for delete all car in big zone( all south of city LS).. 

You have a idea ?
