### ISSUE TITLE
Question about combozones

### ISSUE THREAD

**Issue by Djowman** [mkafrin/PolyZone#45]
So i'm trying to make an alarm script for the VIP's houses but is like 40 polyzones and i want to know if is possible to create combozones  for polyzones...

The script is going to notify the house owner if anyone try to get in the house.

So i just need to the polyzone give the name of the zone if it's possible to create an combozones for polyzones

**Comment by Djowman** [comment]
`cfg = {}

cfg.Homes = {
    ["EX01"] = PolyZone:Create({
        vector2(-3262.5290527344, 814.63146972656),
        vector2(-3226.1159667969, 754.26574707031),
        vector2(-3186.01953125, 772.89715576172),
        vector2(-3134.3029785156, 792.33850097656),
        vector2(-3203.3911132812, 847.09246826172)
    },{ name="EX01", minZ = 5.9308080673218, maxZ = 25.189178466797, debugGrid = true } ),

}`

`
Citizen.CreateThread(function()
    while true do
        local ped = PlayerPedId()
        local coords = GetEntityCoords(ped)
        for k,v in pairs(cfg.Homes) do
            if v:isPointInside(coords) then
                print("inside")
                print(k)
            end
        end
        Citizen.Wait(500)
    end
end)  
`
My code Right Now

**Comment by mkafrin** [comment]
A combozone supports any type of zone (except EntityZone), so polyzones would work just fine, though in general polyzones are the most expensive zone so I usually nudge people towards boxzones and circlezones. You can find more info about how to use combozones here https://github.com/mkafrin/PolyZone/wiki/ComboZone. You probably want to use onPlayerInOut (or onPlayerInOutExhaustive if your zones overlap at all). It triggers a callback when the player enters or leaves a zone and provides the zone itself so you can get it's name, or w/e is stored on it.

**Comment by mkafrin** [comment]
@Djowman Closing for now. Feel free to re-open if you have further questions.
