### ISSUE TITLE
LEFT+ALT is not working in resizing, QB

### ISSUE THREAD

**Issue by f9ariel** [mkafrin/PolyZone#52]
i tried to resize the width when creating a box, but it seems not to work on qb, i wish you could help me on this thanks

**Comment by SSSSAMIIII** [comment]
i am also having this problem cant resize width

**Comment by mkafrin** [comment]
All the controls work fine for me on a clean server. The last time someone had this issue they unbound or changed the binding of the keybind we used to attach to the keys. For Left Alt make sure the "Character Selector" input is set to Left Alt (its default), seen [here](https://i.ytimg.com/vi/1vefXTWN3I4/maxresdefault.jpg).

It's also possible QB is doing something to take over the controls, but that's not something I can fix.
