### ISSUE TITLE
Error with PoliZone

### ISSUE THREAD

**Issue by frebespinal** [mkafrin/PolyZone#58]
SCRIPT ERROR: @PolyZone/BoxZone.lua:76: attempt to index a nil value (local 'center')
![Screenshot 2022-04-30 022844](https://user-images.githubusercontent.com/18050605/166094567-1882d5be-be90-475e-9ca8-490f16c56662.png)

**Comment by mkafrin** [comment]
If you look at where this error is coming from and the error above it, it's a `qb-target` (or maybe `lj_inventory`?) error. The error `nil value (local 'center')` probably means somewhere you or qt-target is trying to create a BoxZone but is passing a nil `center` value.
