### ISSUE TITLE
Need Help!

### ISSUE THREAD

**Issue by DistrictZion** [mkafrin/PolyZone#63]
How can I give a specific colour to the wall and change its opacity? [in debug]
I tried a lot and I'm not changing it right

**Comment by mkafrin** [comment]
You can see the wiki for detailed documentation on creating zones and their options, including the `debugColors` options: https://github.com/mkafrin/PolyZone/wiki/PolyZone.

If you create a zone, you can pass a `debugColors` table that has `walls`, `outline`, and `grid` options. You can read the documentation for more info. Currently there is no way to set alpha however. An example is below that changes the wall colors to purple:

```lua
local pinkcage = PolyZone:Create({
    vector2(328.41662597656, -189.42219543457),
    vector2(347.90512084961, -196.81504821777),
    vector2(336.11190795898, -227.95924377441),
    vector2(306.11798095703, -216.42715454102),
    vector2(314.41293334961, -194.19380187988),
    vector2(324.84567260742, -198.19834899902)
}, {
    name="pink_cage",
    minZ=51.0,
    maxZ=62.0,
    debugColors={
        walls={255,0,255},
    }
})
```
