### ISSUE TITLE
I don't understand.

### ISSUE THREAD

**Issue by MysticStyxxx** [mkafrin/PolyZone#73]
![image](https://user-images.githubusercontent.com/125986062/222951371-4ae03c58-0284-4d93-bd87-8c9e6149715f.png)
Please help

**Comment by MysticStyxxx** [comment]
![image](https://user-images.githubusercontent.com/125986062/222951408-288a0d45-8623-4e4d-b276-0ac1ab683621.png)

**Comment by techy2493** [comment]
Had a similar problem make sure Polyzone is in your dependencies.

**Comment by mkafrin** [comment]
It seems like from this that PolyZone's scripts aren't loading properly. Are there any error messages that indicate this? Are you sure you have PolyZone in your resources and are starting the resource before the resource that is using it?
