### ISSUE TITLE
When trying to use qb-target in server I keep getting this error

### ISSUE THREAD

**Issue by Bxndii23** [mkafrin/PolyZone#75]
Zones are already set , dont know whats wrong.
![helpoo](https://user-images.githubusercontent.com/129241901/228406963-ad67a597-0b08-4e32-a3fd-29f7e7b6bd84.png)

**Comment by mkafrin** [comment]
This is an error in qb-target, not PolyZone, as mentioned by the offending file and line number in the error message.
