### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by Exyztence** [mkafrin/PolyZone#78]
Hi, I am using polyzone on qb-core, and players by default have an access to command /pzcreate.
How can I remove it?

**Comment by mkafrin** [comment]
There's many ways but probably the simplest is you can wrap everything in `creation/client/commands.lua` with this:

```lua
local enableCommands = false
if enableCommands then
 -- Existing code goes here
end
```
then just set `enableCommands` to true when developing locally, but leave it as false normally.

**Comment by Exyztence** [comment]
oh didnt think about it, easy fix, done it, thanks!
