### ISSUE TITLE
[QUESTION] Is there any way to edit inside the zone?

### ISSUE THREAD

**Issue by hoaaiww** [mkafrin/PolyZone#82]
So I have a big zone for a lawn mower script and I would like to cut out the dirt and gravel areas. Is there any way to cut little zones out?

**Comment by mkafrin** [comment]
You could do this in two ways.

1. Use a PolyZone and just set the points to go around the inner zones (this could get complicated and be hard to upkeep if those inner zones change)
2. Have inner and outer zones. Then both can be checked to determine what to do. Aka "if inside outer zone, but not inside inner zones, do x"

Option 2 would probably be simpler to maintain and handle.
