### ISSUE TITLE
[Potential Bug?]

### ISSUE THREAD

**Issue by Spudgun** [mkafrin/PolyZone#85]
When I try to run the following code snippet I am getting an error. Is this the correct functionality, if not would you know why I am getting this error?

```
local VariableName = BoxZone:Create(vector3(481.28, -1317.51, 28.58), 7.0, 5.0, {
    name = "NameofZone",
    heading = 296.06,
    offset = {0.0, 0.0, 0.0},
    scale = {1.0, 1.0, 1.0},
    debugPoly = true,
})

print(VariableName.isPointInside(GetEntityCoords(PlayerPedId())))
```
        
**Error**
![image](https://github.com/mkafrin/PolyZone/assets/3261320/ce67a3f8-9835-48f5-a7b7-83c756657492)

**Comment by mkafrin** [comment]
Probably cause you're not using `:` when calling methods on `VariableName`. Try the following:
```lua
print(VariableName:isPointInside(GetEntityCoords(PlayerPedId())))
```

**Comment by Spudgun** [comment]
> Probably cause you're not using `:` when calling methods on `VariableName`. Try the following:
> 
> ```lua
> print(VariableName:isPointInside(GetEntityCoords(PlayerPedId())))
> ```

... thank you.. No idea how I missed something so simple.

**Comment by Spudgun** [comment]
> Probably cause you're not using `:` when calling methods on `VariableName`. Try the following:
> 
> ```lua
> print(VariableName:isPointInside(GetEntityCoords(PlayerPedId())))
> ```

... thank you.. No idea how I missed something so simple.
