### ISSUE TITLE
Regarding Issue #90

### ISSUE THREAD

**Issue by GttMone** [mkafrin/PolyZone#93]
Regarding Issue #90 
Actually ps-zones doesn't have an export for testing if a point is inside a zone and the export for creating Boxzone and circlezone doesn't support javascript, as it doesn’t convert the coordinates { x: 1, y: 1 } to a vector. Could you recommend me another pz manager script that does all of that or give me an estimate when you're gonna make an official one?

**Comment by mkafrin** [comment]
> Actually ps-zones doesn't have an export for testing if a point is inside a zone

Yeah the point of the script is it manages this for you and triggers events when the player enters and exits zones. Do you actually have a case where you need to test a point that is other than the player's position?

> the export for creating Boxzone and circlezone doesn't support javascript, as it doesn’t convert the coordinates { x: 1, y: 1 } to a vector

This is more of an issue, though would be very easy to fix, so not sure it's worth throwing out over that.

Not really familiar with others atm, but I'm sure you could find many by just searching on github for combozone or something like that. I don't have any current plans to make an official one, but might get to it if I have some free time.

**Comment by GttMone** [comment]
Thank you for the reply! Yes, I do have a case where I need to test a point that is other than the player's position. The other day I was making a script where a player had to interact with another player in the same zone. So it would get the closest player and check if they are in the zone.

I'll look into other pz manager resources on github and thank you for your time :)
