### ISSUE TITLE
polyzoones

### ISSUE THREAD

**Issue by Koikegmo** [mkafrin/PolyZone#97]
hi sorry if thisd not in the right chat/discord. i have a problem with polyzones when i try and scroll down to turn the zone to size  it . it does nothing but everything else worked fine. i had a friend fly in the city and try making and they had no problem turn the zone with the scroll down . Does anyone know how to fix

**Comment by mkafrin** [comment]
If someone else was able to do it, I'm guessing you either have a scroll down related keybind changed to something else (it currently uses the "next radio station" input, or the server has some resource that is enabling the control (PZ attempts to disable it then check if it's pressed). Either way, seems unrelated to PZ itself.
