### ISSUE TITLE
REDM BlockWeaponThisFrame - nil value

### ISSUE THREAD

**Issue by timliesenhoff** [mkafrin/PolyZone#99]
Hey Hello.
there is a problem with BlockWeaponThisFrame 
BlockWeaponThisFrame - nil value?
i checked native docs: https://docs.fivem.net/natives/?_0x0AFC4AF510774B47
relaced it. but still the same. also restarted server etc.
![BlockWeaponThisFrame](https://github.com/mkafrin/PolyZone/assets/18054341/b2dfe535-70b9-42a9-929b-d89c94723b4b)

**Comment by mkafrin** [comment]
PolyZone does not support REDM officially. I think there are some forks that make the changes necessary to support it, but I've never looked at them so use at your own risk.
